import { images } from "./imageUrls";

export const destinations = [
  {
    id: 1,
    slug: "bali",
    name: "Bali",
    country: "Indonesia",
    continent: "Asia",
    rating: 4.9,
    featured: true,
    image: images.destinations.bali,
    description: "Tropical beaches and vibrant culture",
  },
  {
    id: 2,
    slug: "paris",
    name: "Paris",
    country: "France",
    continent: "Europe",
    rating: 4.8,
    featured: true,
    image: images.destinations.paris,
    description: "City of Lights and timeless romance",
  },
  {
    id: 3,
    slug: "SwissAlps",
    name: "Swiss Alps",
    country: "Switzerland",
    continent: "Europe",
    rating: 4.9,
    featured: true,
    image: images.destinations.swiss,
    description: "Snow-capped mountains and scenic villages",
  },
  {
    id: 4,
    slug: "tokyo",
    name: "Tokyo",
    country: "Japan",
    continent: "Asia",
    rating: 4.8,
    featured: true,
    image: images.destinations.tokyo,
    description: "Modern city blended with tradition",
  },
  {
    id: 5,
    slug: "new-york",
    name: "New York",
    wikiTitle: "New York City",
    country: "USA",
    continent: "North America",
    rating: 4.2,
    featured: true,
    image: images.destinations.newyork,
    description: "Dazzling skyline, endless urban adventure.",
  },
  {
    id: 6,
    slug: "goa",
    name: "Goa",
    country: "India",
    continent: "Asia",
    rating: 4.7,
    featured: true,
    image: images.destinations.goa,
    description: "Sun, sand, history, and spice",
  },
  {
    id: 7,
    slug: "rome",
    name: "Rome",
    country: "Italy",
    continent: "Europe",
    rating: 4.8,
    featured: false,
    image: "https://picsum.photos/400/300?random=7",
    description: "Ancient ruins and delicious pasta",
  },
  {
    id: 8,
    slug: "cape-town",
    name: "Cape Town",
    country: "South Africa",
    continent: "Africa",
    rating: 4.7,
    featured: false,
    image: "https://picsum.photos/400/300?random=8",
    description: "Stunning coastlines and rich history",
  },
  {
    id: 9,
    slug: "sydney",
    name: "Sydney",
    country: "Australia",
    continent: "Oceania",
    rating: 4.8,
    featured: false,
    image: "https://picsum.photos/400/300?random=9",
    description: "Iconic harbor and sunny beaches",
  },
  {
    id: 10,
    slug: "rio-de-janeiro",
    name: "Rio de Janeiro",
    country: "Brazil",
    continent: "South America",
    rating: 4.6,
    featured: false,
    image: "https://picsum.photos/400/300?random=10",
    description: "Vibrant carnivals and sandy shores",
  },
  {
    id: 11,
    slug: "kyoto",
    name: "Kyoto",
    country: "Japan",
    continent: "Asia",
    rating: 4.9,
    featured: false,
    image: "https://picsum.photos/400/300?random=11",
    description: "Historic temples and serene gardens",
  },
  {
    id: 12,
    slug: "machu-picchu",
    name: "Machu Picchu",
    country: "Peru",
    continent: "South America",
    rating: 4.9,
    featured: false,
    image: "https://picsum.photos/400/300?random=12",
    description: "Ancient Incan citadel in clouds",
  },
  {
    id: 13,
    slug: "santorini",
    name: "Santorini",
    country: "Greece",
    continent: "Europe",
    rating: 4.8,
    featured: false,
    image: "https://picsum.photos/400/300?random=13",
    description: "White buildings overlooking blue seas",
  },
  {
    id: 14,
    slug: "dubai",
    name: "Dubai",
    country: "UAE",
    continent: "Asia",
    rating: 4.7,
    featured: false,
    image: "https://picsum.photos/400/300?random=14",
    description: "Futuristic architecture and luxury shopping",
  },
  {
    id: 15,
    slug: "banff",
    name: "Banff",
    country: "Canada",
    continent: "North America",
    rating: 4.9,
    featured: false,
    image: "https://picsum.photos/400/300?random=15",
    description: "Majestic peaks and turquoise lakes",
  },
  {
    id: 16,
    slug: "istanbul",
    name: "Istanbul",
    country: "Turkey",
    continent: "Europe",
    rating: 4.7,
    featured: false,
    image: "https://picsum.photos/400/300?random=16",
    description: "Where east beautifully meets west",
  },
  {
    id: 17,
    slug: "phuket",
    name: "Phuket",
    country: "Thailand",
    continent: "Asia",
    rating: 4.6,
    featured: false,
    image: "https://picsum.photos/400/300?random=17",
    description: "Tropical paradise with vibrant nightlife",
  },
  {
    id: 18,
    slug: "barcelona",
    name: "Barcelona",
    country: "Spain",
    continent: "Europe",
    rating: 4.8,
    featured: false,
    image: "https://picsum.photos/400/300?random=18",
    description: "Unique architecture and lively streets",
  },
  {
    id: 19,
    slug: "marrakech",
    name: "Marrakech",
    country: "Morocco",
    continent: "Africa",
    rating: 4.6,
    featured: false,
    image: "https://picsum.photos/400/300?random=19",
    description: "Bustling souks and stunning palaces",
  },
  {
    id: 20,
    slug: "queenstown",
    name: "Queenstown",
    country: "New Zealand",
    wikiTitle: "Queenstown, New Zealand",
    continent: "Oceania",
    rating: 4.9,
    featured: false,
    image: "https://picsum.photos/400/300?random=20",
    description: "Thrill seekers ultimate scenic paradise",
  },
  {
    id: 21,
    slug: "reykjavik",
    name: "Reykjavik",
    country: "Iceland",
    continent: "Europe",
    rating: 4.8,
    featured: false,
    image: "https://picsum.photos/400/300?random=21",
    description: "Geothermal wonders and northern lights",
  },
  {
    id: 22,
    slug: "cairo",
    name: "Cairo",
    country: "Egypt",
    continent: "Africa",
    rating: 4.5,
    featured: false,
    image: "https://picsum.photos/400/300?random=22",
    description: "Timeless pyramids and desert sands",
  },
  {
    id: 23,
    slug: "amalfi-coast",
    name: "Amalfi Coast",
    country: "Italy",
    continent: "Europe",
    rating: 4.9,
    featured: false,
    image: "https://picsum.photos/400/300?random=23",
    description: "Cliffside villages and lemon groves",
  },
  {
    id: 24,
    slug: "petra",
    name: "Petra",
    country: "Jordan",
    continent: "Asia",
    rating: 4.8,
    featured: false,
    image: "https://picsum.photos/400/300?random=24",
    description: "Ancient city carved in stone",
  },
  {
    id: 25,
    slug: "maldives",
    name: "Maldives",
    country: "Maldives",
    continent: "Asia",
    rating: 4.9,
    featured: false,
    image: "https://picsum.photos/400/300?random=25",
    description: "Overwater bungalows and clear waters",
  },
  {
    id: 26,
    slug: "grand-canyon",
    name: "Grand Canyon",
    country: "USA",
    continent: "North America",
    rating: 4.9,
    featured: false,
    image: "https://picsum.photos/400/300?random=26",
    description: "Breathtaking vast red rock canyons",
  }
];